<!doctype html>
<!-- Software Engineering Team 8 -->
<!-- Last Update: 2/18/15 -->
<!-- Agent Dashboard Page -->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Agent | Overview</title>

    <!-- Bootstrap core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
	

    <!-- Custom styles for this template - Specific to the dashboard-->
    <link href="../../css/Dashstyle.css" rel="stylesheet">

  </head>

  <body>
    <!-- Current reference links direct to '#' until a page is created for them. This is static and refers to the current page -->


    <!-- START NAVIGATION - HEADER -->
    <?php
        require_once("./static/navigation-header.php")
    ?>
    <!-- END NAVIGATION - HEADER -->

    <!-- Contains and organizes the remaining page -->
    <div class="container-fluid">
      <div class="row">
	<!-- START NAVIGATION - SIDEBAR -->
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Delivery History</a></li>
            <li><a href="#">View Requests</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Route</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Route Management</a></li>
            <li><a href="">Delivery Account Management</a></li>
            <li><a href="./Customer-Management">Customer Management</a></li>
            <li><a href="./Publication-Management">Publication Management</a></li>
          </ul>
        </div>
	<!-- END NAVIGATION - SIDEBAR -->

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Overview</h1>
          
          <h2 class="sub-header">Your Customer Delivery List for
	    <div class="btn-group">
 	      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
   			 Today <span class="caret"></span>
			<span class="sr-only">Toggle Dropdown</span>
  	      </button>
  	      <ul class="dropdown-menu" role="menu">
    	        <li><a href="#">Tomorrow</a></li>
	        <li><a href="#">All Customers</a></li>
	      </ul>
	    </div>
	  </h2>

	  <!-- START TABLE - CUSTOMER LIST -->
	  <!-- This is currently static, will be dynamically generated by PHP from MySQL entries -->           
          <div class="table-responsive">
            <table class="table table-striped">
	      <!-- Table header -->
              <thead>
                <tr>
                  <th>Customer ID #</th>
                  <th>Name</th>
                  <th>Address</th>
		  <th>Delivery Status 
			<a href="./">
                        <span class="glyphicon glyphicon-pencil pull-right" aria-hidden="true"></span></a></th>
                  <th>Subscriptions</th>
                  <th>Billing</th>
                </tr>
              </thead>

	      <!-- Table data -->
              <tbody>
                <tr>
                  <td>4468</td>
                  <td>Jim Basling</td>
                  <td>540 Mullica Hill Road, NJ</td>
		  <td>Not Delivered <a href="./">
                        <span class="glyphicon glyphicon-pencil pull-right" aria-hidden="true"></span></a></th>
                  <td><a href="./">
			<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a></td>
                  <td><a href="./">
                        <span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span></a></td>
                </tr>
		<tr>
                  <td>4469</td>
                  <td>Sally Livers</td>
                  <td>542 Mullica Hill Road, NJ</td>
		  <td>On Vacation <a href="./">
                        <span class="glyphicon glyphicon-pencil pull-right" aria-hidden="true"></span></a></th>
                  <td><a href="./">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a></td>
                  <td><a href="./">
                        <span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span></a></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Local files also load quicker -->
    <script src="../../js/bootstrap.min.js"></script>
    <script src="../../js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

